### ISSUE TITLE
beta3 install issues

### ISSUE THREAD

**Issue by macmanes** [Blahah/transrate#131]
Working with the new beta3 binary

    >transrate --version
    1.0.0.beta3

running:

    transrate -t 10 -a new.trinity.20M.ec.P2.Trinity.fasta \
    -r ../Mus_musculus.GRCm38.pep.all.fa -l /mouse/feeding/SRR797058.P2_1P.fq \
    -i /mouse/feeding/SRR797058.P2_2P.fq

error:
    
    Dependencies are missing:
    - blastplus (2.2.[0-9])
    To install all missing dependencies, run:
    transrate --install-deps

install-deps

    transrate --install-deps
    Error: option '--install-deps' needs a parameter.
    transrate --install-deps all

**Comment by Blahah** [comment]
thanks, fixed in 4f663faed9eca1c3530849165beb7f43071e336b and 2223e6ae8de1f4d7baf1b96e5e3aa3cc189d24b5
