### ISSUE TITLE
What does this error mean? Error: option '-r' specified multiple times

### ISSUE THREAD

**Issue by amabdelhaliem** [Blahah/transrate#144]

**Comment by Blahah** [comment]
It means exactly what it says - that you specified the `-r` argument multiple times in the same command. Can you paste your command here?

**Comment by amabdelhaliem** [comment]
WOW that's really a quick response!
this is the command causing the problem:
~/programs/transrate-1.0.0-linux-x86_64/transrate --assembly ~/db/Fo2-Fo3-deNovo/trinity_out_dir/Trinity.fasta --left left.fq --right right.fq -threads 30 --outfile Transrate_out

**Comment by amabdelhaliem** [comment]
thanks.

**Comment by Blahah** [comment]
the problem is that you used only a single `-` before `threads` - it should be `--threads`. Arguments with a single `-` are treated as single-letters arguments, so it was interpreted as `-t -h -r -e -a -d -s` :)

The full command you want is...

```
~/programs/transrate-1.0.0-linux-x86_64/transrate --assembly ~/db/Fo2-Fo3-deNovo/trinity_out_dir/Trinity.fasta --left left.fq --right right.fq --threads 30 --outfile Transrate_out
```

**Comment by amabdelhaliem** [comment]
Loading assembly :)
fantastic, you are right, thanks Richard.

**Comment by Blahah** [comment]
great! enjoy transrate :)
