### ISSUE TITLE
Create a tidy directory structure to contain interim files

### ISSUE THREAD

**Issue by Blahah** [Blahah/transrate#148]
Currently, passing in multiple assemblies with the same filename, but in different directories will break transrate. This is because the filename (without the path) is used as the identifier when creating interim files.

Also, the working directory fills up with lots of files. This is ugly and makes debugging and interpretation harder for users.

The solution should be to create a neat directory structure. This could use a `transrate_results` subdirectory in the working directory. This directory would contain a single directory per assembly, with the unique part of each assembly's path, with `/` replaced by `_`.

So for example, if the user passed in:

```
transrate --assembly /assemblies/rice/oases/contigs.fa,/assemblies/maize/trinity.fa
```

the following structure would be created:

```
transrate_results
  - rice_oases
    - contigs.csv
    - ...etc.
  - maize_trinity
    - contigs.csv
    - ...etc.
```

**Comment by rozovr** [comment]
one thing that was odd to me was that this
-o, --outfile=<s>             Prefix filename to use for CSV output (default: transrate)
applies only to CSV files and not all the outputs produced

**Comment by Blahah** [comment]
noted - I think we will eliminate the `-o` argument once this new structure is used, as it will not really be needed (it's easy to just rename the `transrate_results` if necessary)

**Comment by rozovr** [comment]
Why not use it to specify the output path (or prefix) for everything? You can keep the working directory as the default

**Comment by Blahah** [comment]
that seems a reasonable idea

**Comment by Blahah** [comment]
@rozovr thanks, I implemented your idea and it will be in the next release
