### ISSUE TITLE
Transrate and how the number of contigs with an ORF is defined

### ISSUE THREAD

**Issue by amabdelhaliem** [blahah/transrate#158]
Dear Richard,

Thanks for your very helpful tool Transrate. I was wondering how it defines the number of contigs with an ORF (n with orf ===>the number of contigs that had an open reading frame). Does this number mean the total number of unique ORFs in the assembly? And how does it define an ORF? Is it the traditional definition that it has to have start and stop codons only or does it also require the presence of a stop codon before the start codon to make sure that it is a complete protein, like how Transdecoder, for example, does? 
I have a pre-estimation for the number of expected genes in the transcriptome of my organism and I was wondering if the "n with ORF" reflect how many genes are found in the assembly and thus whether I am approaching the expected estimation or not!

Thanks.

**Comment by zagorGit** [comment]
same question, as we are getting underestimated no. of ORF on sequences with defined ORFs

**Comment by blahah** [comment]
Oof, sorry, this has gone unanswered for a long time.

Please see #239 where we will get this resolved.

Thanks for using transrate!
