### ISSUE TITLE
Installation docs out-of-date wrt --install-deps

### ISSUE THREAD

**Issue by ctb** [Blahah/transrate#164]
http://hibberdlab.com/transrate/installation.html makes no mention of an argument to --install-deps, but:

```
% transrate --install-deps
Error: option '--install-deps' needs a parameter.
Try --help for help.
```

**Comment by ctb** [comment]
Seems like just specifying 'ref' works?

**Comment by Blahah** [comment]
Oh yeah, thanks for report.

`--help` is correct:

```
  --install-deps=<s>        Install any missing dependencies. One of [read, ref, all]
```

**Comment by ctb** [comment]
```
% transrate -a nema.fa --left=$LIST1 --right=$LIST2
Dependencies are missing:
  - snap (1.0beta.18)
To install all missing dependencies, run:
  transrate --install-deps all
If you only want the read-metrics dependencies:
  transrate --install-deps read
Or if you only want the reference-metrics dependencies:
  transrate --install-deps ref
% transrate --install-deps=read            [ERROR] 2015-11-01 17:14:10 : install-deps read is not valid. You must specify one of: ref.
% transrate --install-deps=ref
Checking dependencies
All dependencies installed
```

help? :)

**Comment by ctb** [comment]
(Trying to update transrate to use snap 1.0beta.20, which I compiled for my own machine.)

**Comment by ctb** [comment]
Note also

```
OPTIONS:
  --assembly=<s>            Assembly file(s) in FASTA format, comma-separated
  --left=<s>                Left reads file(s) in FASTQ format, comma-separated
  --right=<s>               Right reads file(s) in FASTQ format,
                            comma-separated
  --reference=<s>           Reference proteome or transcriptome file in FASTA
                            format
  --threads=<i>             Number of threads to use (default: 8)
  --merge-assemblies=<s>    Merge best contigs from multiple assemblies into
                            file
  --output=<s>              Directory where results are output (will be
                            created) (default: transrate_results)
  --loglevel=<s>            Log level. One of [error, info, warn, debug]
                            (default: info)
  --install-deps=<s>        Install any missing dependencies. One of [ref]
  --examples                Show some example commands with explanations
```

just reports wanting [ref]

**Comment by Blahah** [comment]
wait, what version of transrate do you have?

**Comment by Blahah** [comment]
oh... it's because it's the binary package, which comes with all the read deps already installed. So the only option is to install the ref dependencies

**Comment by ctb** [comment]
```
%  transrate --version
1.0.1
```

On Sun, Nov 01, 2015 at 09:43:45AM -0800, Richard Smith-Unna wrote:
> wait, what version of transrate do you have?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Blahah/transrate/issues/164#issuecomment-152848229
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by Blahah** [comment]
so to make transrate use a version you compiled...

1. `cd $(dirname $(which transrate ))`
2. move your compiled `snap-aligner` to `./bin`
3. edit `./lib/app/deps/deps.yaml` to update the SNAP version

**Comment by ctb** [comment]
On Sun, Nov 01, 2015 at 09:47:42AM -0800, Richard Smith-Unna wrote:
> so to make transrate use a version you compiled...
> 
> 1. `cd $(dirname $(which transrate ))`
> 2. move your compiled `snap-aligner` to `./bin`
> 3. edit `./lib/app/deps/deps.yaml` to update the SNAP version

Ahh, #3 important.
