### ISSUE TITLE
support for single-end reads for read mapping metrics

### ISSUE THREAD

**Issue by wfaalajr** [Blahah/transrate#167]
just wondering if you're planning to add an option wherein single-end reads are also supported just like in trinity (-single)...

thanks!

**Comment by macmanes** [comment]
single end reads add so little (e.g., no) information to these evaluation metrics, I think probably unlikely this functionality will be added.

**Comment by Blahah** [comment]
indeed, single-end reads are not very useful. We actually drop them rather than use them in our assemblies, and we have no plans to use them in transrate because almost all the good quality information comes from the paired-end reads.
