### ISSUE TITLE
suggested sed to fix assembly fasta header does not work

### ISSUE THREAD

**Issue by ljcohen** [Blahah/transrate#172]
I ran transrate with a fasta file from Trinity and got the error below. When I fixed the fasta with the suggested `sed 's/\|/_/' Trinity.fasta > Trinity.fixed.fa`, it appeared to insert '_' before each line:

On Ubuntu 14.04

root@ip-172-31-4-46:/mnt/mmetsp/Micromonas_pusilla/SRR1300455# head Trinity.fasta
>TR1|c0_g1_i1 len=271 path=[2773:0-246 2774:247-270] [-1, 2773, 2774, -2]
CGAGACGGAGACGTGCGCCGCGATGAGCTTCTCCGGCGTGCGCGAGGAGCGCCTGAAGAC
GCCCCTGCCGAAGTCGCCCCCCCCGAAGTCGCCCGACGCGCCGAGCCCCGCGAAGGCCGT
GCTGCACAGCCCTTCGTTCGAGGCGCCCAACGCCCTGGATGCGCAATTCTCGGCTCTGGT
GCACGACATCCAGCAGCGTTTAGCGCTTTTGGCGCGCGCGCCCACCATCCGCGTCGAGAA
GTGGCTGCGCAAGCTGCACGACCCCGTGTCC
>TR1|c0_g2_i1 len=1148 path=[2772:0-1147] [-1, 2772, -2]
GCAAGCTGCACGACCCCGTGTCCAACGTGACGTGGAAGAAGCTCCGCAACGACTACGCGC
GCCTGCTGCGGCACAACCTGTCAAACGGCGCGACCAGCCCCCCGTTCGACAAGGCCCCAG
ACGACGGGCCTTTGCGCAATCTGCTTCCGGACGAAAAGGCGCGATTCAAAGGCGACGGCT
root@ip-172-31-4-46:/mnt/mmetsp/Micromonas_pusilla/SRR1300455# transrate -a Trinity.fasta
[ INFO] 2015-12-02 00:13:46 : Loading assembly: /mnt/mmetsp/Micromonas_pusilla/SRR1300455/Trinity.fasta
[ERROR] 2015-12-02 00:13:46 : Non unique fasta identifier found
[ERROR] 2015-12-02 00:13:46 : >TR1
[ERROR] 2015-12-02 00:13:46 : Please make sure there are no duplicate entries in the assembly
[ERROR] 2015-12-02 00:13:46 : Contig name is taken from before the first | or space
[ERROR] 2015-12-02 00:13:46 : If you used Trinity, there is a known bug that breakscontig names to make them non-unique.
[ERROR] 2015-12-02 00:13:46 : You can fix your Trinity assembly by replacing | with _
[ERROR] 2015-12-02 00:13:46 : e.g. `sed 's/\|/_/' Trinity.fa > Trinity.fixed.fa`
[ERROR] 2015-12-02 00:13:46 : Transrate::AssemblyError

I fixed with a sed command suggested by @macmanes 
http://angus.readthedocs.org/en/2015/MacManes_Trinity.html

`sed 's_|_-_g' Trinity.fasta > Trinity.fixed.fa`

root@ip-172-31-4-46:/mnt/mmetsp/Micromonas_pusilla/SRR1300455# sed 's_|_-_g' Trinity.fasta > Trinity.fixed.fa
root@ip-172-31-4-46:/mnt/mmetsp/Micromonas_pusilla/SRR1300455# head Trinity.fixed.fa 
>TR1-c0_g1_i1 len=271 path=[2773:0-246 2774:247-270] [-1, 2773, 2774, -2]
CGAGACGGAGACGTGCGCCGCGATGAGCTTCTCCGGCGTGCGCGAGGAGCGCCTGAAGAC
GCCCCTGCCGAAGTCGCCCCCCCCGAAGTCGCCCGACGCGCCGAGCCCCGCGAAGGCCGT
GCTGCACAGCCCTTCGTTCGAGGCGCCCAACGCCCTGGATGCGCAATTCTCGGCTCTGGT
GCACGACATCCAGCAGCGTTTAGCGCTTTTGGCGCGCGCGCCCACCATCCGCGTCGAGAA
GTGGCTGCGCAAGCTGCACGACCCCGTGTCC
>TR1-c0_g2_i1 len=1148 path=[2772:0-1147] [-1, 2772, -2]
GCAAGCTGCACGACCCCGTGTCCAACGTGACGTGGAAGAAGCTCCGCAACGACTACGCGC
GCCTGCTGCGGCACAACCTGTCAAACGGCGCGACCAGCCCCCCGTTCGACAAGGCCCCAG
ACGACGGGCCTTTGCGCAATCTGCTTCCGGACGAAAAGGCGCGATTCAAAGGCGACGGCT
root@ip-172-31-4-46:/mnt/mmetsp/Micromonas_pusilla/SRR1300455# transrate -a Trinity.fixed.fa
[ INFO] 2015-12-02 00:27:40 : Loading assembly: /mnt/mmetsp/Micromonas_pusilla/SRR1300455/Trinity.fixed.fa
[ INFO] 2015-12-02 00:27:42 : Analysing assembly: /mnt/mmetsp/Micromonas_pusilla/SRR1300455/Trinity.fixed.fa
[ INFO] 2015-12-02 00:27:42 : Results will be saved in /mnt/mmetsp/Micromonas_pusilla/SRR1300455/transrate_results/Trinity.fixed
[ INFO] 2015-12-02 00:27:42 : Calculating contig metrics...
[ INFO] 2015-12-02 00:27:45 : Contig metrics:
[ INFO] 2015-12-02 00:27:45 : -----------------------------------
[ INFO] 2015-12-02 00:27:45 : n seqs                        16048
[ INFO] 2015-12-02 00:27:45 : smallest                        224
[ INFO] 2015-12-02 00:27:45 : largest                       17621
[ INFO] 2015-12-02 00:27:45 : n bases                    17657736
[ INFO] 2015-12-02 00:27:45 : mean len                    1100.31
[ INFO] 2015-12-02 00:27:45 : n under 200                       0
[ INFO] 2015-12-02 00:27:45 : n over 1k                      6597
[ INFO] 2015-12-02 00:27:45 : n over 10k                        8
[ INFO] 2015-12-02 00:27:45 : n with orf                    11620
[ INFO] 2015-12-02 00:27:45 : mean orf percent              88.27
[ INFO] 2015-12-02 00:27:45 : n90                             522
[ INFO] 2015-12-02 00:27:45 : n70                            1035
[ INFO] 2015-12-02 00:27:45 : n50                            1545
[ INFO] 2015-12-02 00:27:45 : n30                            2200
[ INFO] 2015-12-02 00:27:45 : n10                            3610
[ INFO] 2015-12-02 00:27:45 : gc                             0.67
[ INFO] 2015-12-02 00:27:45 : gc skew                         0.0
[ INFO] 2015-12-02 00:27:45 : at skew                        -0.0
[ INFO] 2015-12-02 00:27:45 : cpg ratio                      2.58
[ INFO] 2015-12-02 00:27:45 : bases n                           0
[ INFO] 2015-12-02 00:27:45 : proportion n                    0.0
[ INFO] 2015-12-02 00:27:45 : linguistic complexity          0.17
[ INFO] 2015-12-02 00:27:45 : Contig metrics done in 3 seconds
[ INFO] 2015-12-02 00:27:45 : No reads provided, skipping read diagnostics
[ INFO] 2015-12-02 00:27:45 : No reference provided, skipping comparative diagnostics
[ INFO] 2015-12-02 00:27:45 : Writing contig metrics for each contig to /mnt/mmetsp/Micromonas_pusilla/SRR1300455/transrate_results/Trinity.fixed/contigs.csv
[ INFO] 2015-12-02 00:27:47 : Writing analysis results to assemblies.csv

**Comment by jessicamizzi** [comment]
I am having the same issues as Lisa, and fixed it the same way. This is how I am installing transrate:

`cd
curl -O -L https://bintray.com/artifact/download/blahah/generic/transrate-1.0.1-linux-x86_64.tar.gz
tar xzf transrate-1.0.1-linux-x86_64.tar.gz

export PATH=$PATH:$HOME/transrate-1.0.1-linux-x86_64
echo 'export PATH=$PATH:$HOME/transrate-1.0.1-linux-x86_64' >> ~/.bashrc
export PATH=$PATH:$HOME/transrate-1.0.1-linux-x86_64/bin
echo 'export PATH=$PATH:$HOME/transrate-1.0.1-linux-x86_64/bin' >> ~/.bashrc

transrate --install-deps ref`

After running transrate, I received the suggestion `sed 's/\\|/_/' Trinity.fa > Trinity.fixed.fa`.

To see how this is being run in context, it starts at the point saying "Install Transrate" in this readme: https://github.com/jessicamizzi/ep-streaming
