### ISSUE TITLE
transrate --merge-assemblies option shows error

### ISSUE THREAD

**Issue by sarangian** [Blahah/transrate#175]
I am trying to run transrate with --merge-assemblies option

./transrate --assembly one.fa,two.fa,three.fa,four.fa --merge-assemblies merged_assemblies

This is showing the following error

transrate-1.0.1/lib/app/lib/transrate/cmdline.rb:38:in `block in run': undefined method `zip' for "merged_test":String (NoMethodError)
	from /home/metagenomics/software/transrate-1.0.1/lib/app/lib/transrate/cmdline.rb:33:in `chdir'
	from /home/metagenomics/software/transrate-1.0.1/lib/app/lib/transrate/cmdline.rb:33:in `run'
	from /home/metagenomics/software/transrate-1.0.1/lib/app/bin/transrate:23:in `<main>'

Kindly suggest

**Comment by macmanes** [comment]
Any update on this issue?

**Comment by Blahah** [comment]
cc @cboursnell could you take a look?

**Comment by ADAC-UoN** [comment]
Seem to still be having similar issues. Transrate installed by gem 22/12/16. Any suggestions?
Cheers Rich

[ INFO] 2016-01-22 09:24:52 : Merging assemblies into one file...'merged_assemblies'
/usr/local/lib/ruby/gems/2.0.0/gems/transrate-1.0.1/lib/transrate/cmdline.rb:36:in `block in run': undefined method `zip' for "merged_assemblies":String (NoMethodError)
	from /usr/local/lib/ruby/gems/2.0.0/gems/transrate-1.0.1/lib/transrate/cmdline.rb:31:in `chdir'
	from /usr/local/lib/ruby/gems/2.0.0/gems/transrate-1.0.1/lib/transrate/cmdline.rb:31:in `run'
	from /usr/local/lib/ruby/gems/2.0.0/gems/transrate-1.0.1/bin/transrate:23:in `<top (required)>'
	from /usr/local/bin/transrate:23:in `load'
	from /usr/local/bin/transrate:23:in `<main>'

**Comment by Blahah** [comment]
Fixed in #175, will be in release `1.0.2` later today
