### ISSUE TITLE
Packaging in salmon (on OSX 10.10.5)

### ISSUE THREAD

**Issue by AndrewIrwin** [blahah/transrate#181]
I'm trying to use transrate v 1.0.1 but running into problems with Salmon. The version installed with transrate is 0.4 which (a) gives a warning that it is not the current version and (b) crashes with the unhelpful message "salmon failed".

I installed the current salmon 0.6.0 and replaced the binary in the transrate bin directory, but now I get

[ERROR] 2016-01-25 17:04:42 : Version Info: This is the most recent version of Salmon.
exception : [unrecognised option '--useVBOpt']. Exiting.

[ERROR] 2016-01-25 17:04:42 : Salmon failed

Suggestions for diagnosing the problem and addressing it would be appreciated!

**Comment by rob-p** [comment]
Hi @AndrewIrwin, The unrecognized option is my fault.  Apparently, the `--useVBOpt` option was accidentally removed in the *alignment-based* mode of Salmon in the most recent release.  A new release is imminent, and I'll make sure I re-enable this option.  However, I would not recommend using transrate with a different version of salmon than the one with which it was packaged, as the output format has changed and so there may be incompatibilities.

Regarding the initial error, "salmon failed", this is (I believe) the result of the transrate wrapper recognizing a non-zero return code from salmon.  It's not clear what the actual error is in this case (perhaps taking a look at the Salmon logs would provide more useful information).  I'd also do a sanity check of the bam file being fed to Salmon, as we've seen quite a few issues in the past that were the result of a SNAP failure that then cascaded downstream to Salmon.

**Comment by Blahah** [comment]
@AndrewIrwin I suggest the following to help isolate the problem:

1. delete the transrate output directory that was created when you ran the command that crashed
2. re-run transrate as before, but add `--loglevel debug`

You should now see some more useful information printed to the screen.

**Comment by AndrewIrwin** [comment]
The software terminates without errors when I add the “—loglevel debug” option.

If you are interested, I’d be happy to send you any of the input or output.

Andrew


On Jan 25, 2016, at 5:37 PM, Richard Smith-Unna <notifications@github.com<mailto:notifications@github.com>> wrote:


@AndrewIrwin<https://github.com/AndrewIrwin> I suggest the following to help isolate the problem:

  1.  delete the transrate output directory that was created when you ran the command that crashed
  2.  re-run transrate as before, but add --loglevel debug

You should now see some more useful information printed to the screen.

**Comment by Blahah** [comment]
Did you delete the output directory before running with `--loglevel debug`? If not, please do that first and re-run it.

If you had already deleted the output directory, the error was either a one-off (process got killed, etc) or a nondeterministic bug. Unless we see any more cases, we'll assume it's the former :)

**Comment by AndrewIrwin** [comment]
Richard,

A clarification: the error still occurs, sometimes. I’ve run the following command 4 times and had 2 error-free runs:

transrate --assembly Trinity.fixed.fasta      --loglevel debug   --left ../norm/global/left.norm.fq  --right ../norm/global/right.norm.fq  > ${DIR}/transrate_assembly_reads.log 2>&1

I get a different number of good contigs each time.

The output and debug message from one failure includes:
- Zlib magic number failure (once or twice) and
- "Salmon failed” with a traceback

[ INFO] 2016-01-26 12:20:14 : Loading assembly: /Users/airwin/Desktop/processReads/Koester/ccmp158/trinity_out_dir/Trinity.fixed.fasta
[ INFO] 2016-01-26 12:20:26 : Analysing assembly: /Users/airwin/Desktop/processReads/Koester/ccmp158/trinity_out_dir/Trinity.fixed.fasta
[ INFO] 2016-01-26 12:20:26 : Results will be saved in /Users/airwin/Desktop/processReads/Koester/ccmp158/trinity_out_dir/transrate_results/Trinity.fixed
[ INFO] 2016-01-26 12:20:26 : Calculating contig metrics...
[ INFO] 2016-01-26 12:20:38 : Contig metrics:
[ INFO] 2016-01-26 12:20:38 : -----------------------------------
[ INFO] 2016-01-26 12:20:38 : n seqs                        66753
[ INFO] 2016-01-26 12:20:38 : smallest                        224
[ INFO] 2016-01-26 12:20:38 : largest                       14195
[ INFO] 2016-01-26 12:20:38 : n bases                    68822604
[ INFO] 2016-01-26 12:20:38 : mean len                     1031.0
[ INFO] 2016-01-26 12:20:38 : n under 200                       0
[ INFO] 2016-01-26 12:20:38 : n over 1k                     23775
[ INFO] 2016-01-26 12:20:38 : n over 10k                       12
[ INFO] 2016-01-26 12:20:38 : n with orf                    30483
[ INFO] 2016-01-26 12:20:38 : mean orf percent              70.12
[ INFO] 2016-01-26 12:20:38 : n90                             412
[ INFO] 2016-01-26 12:20:38 : n70                            1039
[ INFO] 2016-01-26 12:20:38 : n50                            1678
[ INFO] 2016-01-26 12:20:38 : n30                            2445
[ INFO] 2016-01-26 12:20:38 : n10                            4043
[ INFO] 2016-01-26 12:20:38 : gc                             0.38
[ INFO] 2016-01-26 12:20:38 : gc skew                        0.05
[ INFO] 2016-01-26 12:20:38 : at skew                        0.09
[ INFO] 2016-01-26 12:20:38 : cpg ratio                      1.59
[ INFO] 2016-01-26 12:20:38 : bases n                           0
[ INFO] 2016-01-26 12:20:38 : proportion n                    0.0
[ INFO] 2016-01-26 12:20:38 : linguistic complexity          0.18
[ INFO] 2016-01-26 12:20:38 : Contig metrics done in 12 seconds
[ INFO] 2016-01-26 12:20:38 : Calculating read diagnostics...
[ERROR] 2016-01-26 12:24:18 : Version Info: A newer version of Salmon with important new features is availaible.
Please check https://github.com/COMBINE-lab/salmon/releases, for the latest release.
# salmon (alignment-based) v0.4.2
# [ program ] => salmon
# [ command ] => quant
# [ libType ] => { IU }
# [ alignments ] => { /Users/airwin/Desktop/processReads/Koester/ccmp158/trinity_out_dir/transrate_results/Trinity.fixed/left.norm.fq.right.norm.fq.Trinity.fixed.bam }
# [ targets ] => { /Users/airwin/Desktop/processReads/Koester/ccmp158/trinity_out_dir/Trinity.fixed.fasta }
# [ threads ] => { 8 }
# [ sampleOut ] => { }
# [ sampleUnaligned ] => { }
# [ output ] => { . }
# [ useVBOpt ] => { }
# [ useErrorModel ] => { }
Library format { type:paired end, relative orientation:inward, strandedness:unstranded }
Logs will be written to ./logs
numQuantThreads = 4
parseThreads = 4
Checking that provided alignment files have consistent headers . . . done
Populating targets from aln = "/Users/airwin/Desktop/processReads/Koester/ccmp158/trinity_out_dir/transrate_results/Trinity.fixed/left.norm.fq.right.norm.fq.Trinity.fixed.bam", fasta = "/Users/airwin/Desktop/processReads/Koester/ccmp158/trinity_out_dir/Trinity.fixed.fasta" . . .done
Zlib magic number failure
Zlib magic number failure



^M^MESC[0;32mprocessedESC[0;31m 0 ESC[0;32mreads in current roundESC[0;0m^M^MESC
[0;32mprocessedESC[0;31m 151867 ESC[0;32mreads in current roundESC[0;0m
^M^Mkilling thread 0 . . . done^M^Mkilling thread 1 . . . done^M^Mkilling thread
 2 . . . done^M^Mkilling thread 3 . . . done

# observed = 151867 / # required = 50000000ESC[AESC[AESC[AESC[AESC[A[2016-01-26
12:24:16.135] [jointLog] [info]


Completed first pass through the alignment file.
Total # of mapped reads : 151867
# of uniquely mapped reads : 88559
# ambiguously mapped reads : 63308

[2016-01-26 12:24:16.333] [jointLog] [info] Computed 46448 rich equivalence classes for further processing
[2016-01-26 12:24:16.333] [jointLog] [info] starting optimizer
[2016-01-26 12:24:16.389] [jointLog] [info]
Dropping weighted eq class
============================
denom = 0, count = 4
class = { 31058 31061 }
alphas = { 0 0 }
weights = { 0.685735 0.314265 }
============================


[2016-01-26 12:24:16.393] [jointLog] [info] Marked 1 weighted equivalence classes as degenerate
[2016-01-26 12:24:16.399] [jointLog] [info] iteration = 0 | max rel diff. = 17.6147

[ERROR] 2016-01-26 12:24:18 : Salmon failed
[DEBUG] 2016-01-26 12:24:18 : /Users/airwin/sw/transrate-1.0.1-osx/lib/app/bin/transrate:13:in `raise' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/salmon.rb:27:in `run' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/read_metrics.rb:120:in `assign_and_quantify' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/read_metrics.rb:63:in `run' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/transrater.rb:86:in `read_metrics' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/cmdline.rb:461:in `read_metrics' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/cmdline.rb:380:in `block in analyse_assembly' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/cmdline.rb:376:in `chdir' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/cmdline.rb:376:in `analyse_assembly' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/cmdline.rb:38:in `block (2 levels) in run' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/cmdline.rb:37:in `zip' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/cmdline.rb:37:in `block in run' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/cmdline.rb:32:in `chdir' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/lib/transrate/cmdline.rb:32:in `run' /Users/airwin/sw/transrate-1.0.1-osx/lib/app/bin/transrate:23:in `<main>’

Any suggestions would be welcome!

—

The software terminates without errors when I add the “—loglevel debug” option.

If you are interested, I’d be happy to send you any of the input or output.

Andrew


On Jan 25, 2016, at 5:37 PM, Richard Smith-Unna <notifications@github.com<mailto:notifications@github.com>> wrote:


@AndrewIrwin<https://github.com/AndrewIrwin> I suggest the following to help isolate the problem:

  1.  delete the transrate output directory that was created when you ran the command that crashed
  2.  re-run transrate as before, but add --loglevel debug

You should now see some more useful information printed to the screen.

**Comment by Blahah** [comment]
In the next minor release we will update to the latest versions of SNAP and Salmon - hopefully the bug will be fixed in one of those, but if not we can revisit.

**Comment by el42008** [comment]
Hi Richard, 

I am trying to run transrate v 1.0.2 with some reads as evidence for my trinity assembly.

I got the following error:
[ERROR] 2016-04-10 11:08:18 : Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
# salmon (alignment-based) v0.4.2
What should I do?

Cheers
Elena

**Comment by rob-p** [comment]
Hmm, I don't know why that should result in an error, but it looks like salmon can't reach the outside world to check the version. Normally, that's fine (it just prints the above message and continues to quantify).  Does the alignment file produced by SNAP look ok?

**Comment by el42008** [comment]
Hi,

Thanks for replying so quick. The e15359 is when i used teh last version of
transrate. And e15377 it is when use the latest version. In the first one
fails because sailfish and in the second case because of salmon.

Cheers



2016-04-10 16:18 GMT+01:00 Rob Patro <notifications@github.com>:

**Comment by rob-p** [comment]
For e15359, do you mean SNAP?  Sailfish was never part of transrate.  What I mean about the alignment file is, e.g. what is the size of the BAM file written by SNAP, is there any SNAP output in the logs, do you believe the alignment finished successfully, etc?  Unless there is some sort of timeout mechanism of which I'm not aware, failure to resolve the version message alone should cause transrate to fail / exit.  Any thoughts @blahah ?

**Comment by blahah** [comment]
The latest release of transrate [v1.0.3](https://github.com/blahah/transrate/releases/tag/v1.0.3) now includes the latest version of SNAP and Salmon. Hopefully this will solve the problem - if not please re-open the issue. Many thanks for your patience :)
