### ISSUE TITLE
1.02 downloaded transrate install runs in install directory, not working directory.

### ISSUE THREAD

**Issue by ctb** [Blahah/transrate#186]
See instructions here -- https://2016-march-non-model-organism-rnaseq.readthedocs.org/en/latest/n-stats-eval.html.  I have to run:

     transrate --assembly=/mnt/work/rna-assembly.fa

even when my cwd is /mnt/work, because transrate doesn't find the file otherwise:

    transrate --assembly=rnaseq-assembly.fa
    [ERROR] 2016-03-30 13:57:00 : Assembly fasta file does not exist:  /home/ubuntu/transrate-1.0.2-linux-x86_64/rnaseq-assembly.fa

**Comment by Blahah** [comment]
Ah, sorry about this. @macmanes and a couple of other users also pointed this out, and I've not had time to address it. Looking into it now.

**Comment by Blahah** [comment]
Fix will be in v1.0.3
