### ISSUE TITLE
--install-deps help message is annoyingly wrong

### ISSUE THREAD

**Issue by ctb** [Blahah/transrate#187]
```
transrate --assembly=/mnt/work/rna-assembly.fa --reference=/mnt/work/rna-assembly-nodn.fa 
Dependencies are missing:
  - blastplus (2.2.[0-9])
To install all missing dependencies, run:
  transrate --install-deps all
If you only want the read-metrics dependencies:
  transrate --install-deps read
Or if you only want the reference-metrics dependencies: 
  transrate --install-deps ref
ubuntu@ip-172-30-1-60:/mnt/work$ transrate --install-deps all                   
[ERROR] 2016-03-30 13:59:04 : install-deps all is not valid. You must specify one of: ref.
```

On the plus side, once you do specify 'ref' it works ;)

**Comment by Blahah** [comment]
fix will be in v1.0.3

**Comment by KarolisM** [comment]
Hi,

still same error with v1.0.3, downloaded compiled version for linux:

https://bintray.com/artifact/download/blahah/generic/transrate-1.0.3-linux-x86_64.tar.gz

Karolis

**Comment by JohnUrban** [comment]
Yes same here. I'm getting this error using:
https://bintray.com/artifact/download/blahah/generic/transrate-1.0.3-linux-x86_64.tar.gz

I can also confirm that `transrate --install-deps ref` works...

**Comment by rafaeltiveron** [comment]
It seens not working anymore... Do you have a directly link or manual step installation?
