### ISSUE TITLE
File paths must be absolute

### ISSUE THREAD

**Issue by jorvis** [Blahah/transrate#188]
My initial test run failed when I was used relative paths:

```
$ /home/jorvis/transrate/transrate --assembly A1_trinity_oases_merged.fasta --left R1.trimmed.PE.fastq --right R2.trimmed.PE.fastq --merge-assemblies merged_assemblies --threads 24
[ERROR] 2016-04-01 23:58:14 : Assembly fasta file does not exist:  /home/jorvis/transrate-1.0.2-linux-x86_64/A1_trinity_oases_merged.fasta

$ pwd
/local/scratch/aplysia/transrate

$ ls
A1_trinity_oases_merged.fasta  COMMANDS  R1.trimmed.PE.fastq  R2.trimmed.PE.fastq

$ /home/jorvis/transrate/transrate --assembly /local/scratch/aplysia/transrate/A1_trinity_oases_merged.fasta --left /local/scratch/aplysia/transrate/R1.trimmed.PE.fastq --right /local/scratch/aplysia/transrate/R2.trimmed.PE.fastq --merge-assemblies merged_assemblies --threads 24

[Runs successfully]
```

Each option --assembly, --left and --right failed if I just entered the file name, even though my cwd was their directory, and corrected only when I used the full path instead.

**Comment by Blahah** [comment]
See #186 -  the fix has already been pushed and will be in the next release

**Comment by Blahah** [comment]
Also - this issue was introduced in v1.0.2 - 1.0.1 should work fine :)

**Comment by almutwerner** [comment]
For people still using this tool: 
This issue seems to have been reintroduced in v1.0.3. Luckily, providing absolute paths for everything still works
