### ISSUE TITLE
SNAP failed

### ISSUE THREAD

**Issue by jwidmann** [blahah/transrate#190]
Hi,
i get the following Error when running transrate on my assembly:
```
[ERROR] 2016-04-01 16:08:24 : Snap failed
Welcome to SNAP version 1.0beta.18.

mmap failed.
MemMapDataReader: fail to map Tissue5_right.fastq at 0,10388449043
SNAP exited with exit code 1 from line 2233 of file SNAPLib/DataReader.cpp
```
Is this simply because I have too much input reads for SNAP to map,
or is this something else?
This is the command I used:

` transrate --assembly Trinity_allTissues.fasta --left Tissue1_left.fastq,Tissue2_left.fastq,Tissue3_left.fastq,Tissue4_left.fastq,Tissue5_left.fastq --right  Tissue1_right.fastq,Tissue2_right.fastq,Tissue3_right.fastq,Tissue4_right.fastq,Tissue5_right.fastq --threads 8 --output /Transrate`

Any suggestions?
Best wishes

**Comment by blahah** [comment]
SNAP should be able to handle any number of input reads - more likely this is a bug. I am currently working through some SNAP bugs to see if I can pin down what causes them and ask the SNAP developers to fix them.

Have you tried running the same command again? The bug may be non-deterministic, in which case it might work the second time round.

**Comment by jwidmann** [comment]
Yep, tried twice the same command, resulting in the same Error. 
But maybe the third time is the charm, i'll give it another try.
Thanks for your fast reply :)

**Comment by blahah** [comment]
I'm currently working on the next release of transrate which includes various fixes to SNAP - can you try it and see if it solves your problem? Download links below

- [linux](https://www.dropbox.com/s/8tdmderqdz7svqo/transrate-1.0.3-linux-x86_64.tar.gz?dl=0)
- [osx](https://www.dropbox.com/s/g24hvse4glat0k6/transrate-1.0.3-osx.tar.gz?dl=0)

**Comment by blahah** [comment]
Ah, and please make sure to delete the output directory from the earlier runs, or give the new run a different output location.

**Comment by jwidmann** [comment]
Hmm, the next release gives the same error (but line 2283).
Mapping only this specific read set works fine.

**Comment by blahah** [comment]
hi @jwidmann, the latest release of transrate v1.0.3 now includes the latest version of SNAP and Salmon as well as some other bug fixes. Please update and try your analysis again. Hopefully this will solve the problem - if not please re-open the issue. Many thanks for your patience :)

**Comment by Jinjie-Duan** [comment]
Hi, @blahah ,I installed the latest version of transrate v 1.0.3. But I still got the same followoing message about SNAP failed. Would you please help on it? Thanks!
 
[ERROR] 2017-02-23 16:07:32 : Snap failed
Welcome to SNAP version 1.0dev.96.

mmap failed.
MemMapDataReader: fail to map /home/jjduan/python/01highQualityData/withoutN-trimlastbase/110902_SN132_B_L002_R2_GLQ-13b.fastq at 0,1966390515
SNAP exited with exit code 1 from line 2283 of file SNAPLib/DataReader.cpp
