### ISSUE TITLE
Example command doesn't work

### ISSUE THREAD

**Issue by simonvh** [blahah/transrate#192]
```
$ transrate --examples
[...]
# check dependencies and install any that are missing
transrate --install-deps all
[...]
```
when I try this, this results in the following message:

```
$ transrate --install-deps all
[ERROR] 2016-04-13 10:24:44 : install-deps all is not valid. You must specify one of: ref.
```

This using transrate-1.0.2-linux-x86_64.

**Comment by blahah** [comment]
Thanks for reporting this - the reason this doesn't work is that the dependencies are already installed. We need to make that clear in the message.

**Comment by blahah** [comment]
@simonvh we've made the `--install-deps` instructions clearer both on the website and in the `--help` message for [v1.0.3](https://github.com/blahah/transrate/releases/tag/v1.0.3). Thanks again for reporting this.
