### ISSUE TITLE
Installing dependencies with version 1.0.3

### ISSUE THREAD

**Issue by abshah** [blahah/transrate#194]
Hi transrate users/developers,

Recently, I was trying to install transrate version 1.0.3, however, I couldn't get it to install the dependencies. My console output was :

`[root@gaiking transrate]# gem install transrate-1.0.3.gem
Building native extensions.  This could take a while...
Successfully installed transrate-1.0.3
Parsing documentation for transrate-1.0.3
Installing ri documentation for transrate-1.0.3
Done installing documentation for transrate after 0 seconds
1 gem installed
[root@gaiking transrate]# transrate --install-deps=all
Checking dependencies
Installing snap (1.0dev.96)...
/usr/local/rvm/gems/ruby-2.1.0/gems/transrate-1.0.3/bin/transrate:13:in `raise': There was a problem unpacking snap_v1.0dev.96_linux.tar.gz (RuntimeError)

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
	from /usr/local/rvm/gems/ruby-2.1.0/gems/bindeps-1.2.1/lib/unpacker.rb:52:in `block in unpack'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/bindeps-1.2.1/lib/unpacker.rb:35:in `unpack'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/bindeps-1.2.1/lib/bindeps.rb:134:in `unpack'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/bindeps-1.2.1/lib/bindeps.rb:86:in `install_missing'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/bindeps-1.2.1/lib/bindeps.rb:29:in `block (3 levels) in require'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/bindeps-1.2.1/lib/bindeps.rb:20:in `each_pair'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/bindeps-1.2.1/lib/bindeps.rb:20:in `block (2 levels) in require'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/bindeps-1.2.1/lib/bindeps.rb:19:in `chdir'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/bindeps-1.2.1/lib/bindeps.rb:19:in `block in require'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/bindeps-1.2.1/lib/bindeps.rb:18:in `require'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:293:in `install_missing_dependencies'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:258:in `check_dependencies'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:164:in `check_arguments'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:18:in `initialize'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/transrate-1.0.3/bin/transrate:22:in `new'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/transrate-1.0.3/bin/transrate:22:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.0/bin/transrate:22:in `load'
	from /usr/local/rvm/gems/ruby-2.1.0/bin/transrate:22:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'`

**Comment by blahah** [comment]
Hi @abshah this was probably because v1.0.3 was not released yet, and you were building from an unstable state in `master`.

The latest release of transrate [v1.0.3](https://github.com/blahah/transrate/releases/tag/v1.0.3) now includes the latest version of SNAP and Salmon. Hopefully this will solve the problem - if not please re-open the issue. Many thanks for your patience :)
