### ISSUE TITLE
Read Diagnostics, SNAP failing

### ISSUE THREAD

**Issue by JakeGoodall** [blahah/transrate#195]
Hi there, 
Apologies if this is a silly question, but I am still very new to bioinformatics. I have a question regarding the generation of read diagnostics. I've run the example dataset though the 'Getting Started' protocol with no issues, but I can't seem to get my actual dataset to work. I can examine my contigs without any issues but when I try to add in my RNA-seq reads (Rcorrected and quality controlled using trimmomatic) I get the following error message: 
```
[ INFO] 2016-04-27 12:00:53 : Calculating read diagnostics...
[ERROR] 2016-04-27 12:00:53 : Snap failed
Welcome to SNAP version 1.0beta.18.

Unable to open file 'Trinity.fixed/GenomeIndex' for read.
Index load failed, aborting.
mmap failed.
MemMapDataReader: fail to map /trimmomatic/paired/R2_trimmed_paired.fastq at 0,2726996548
SNAP exited with exit code 1 from line 2233 of file SNAPLib/DataReader.cpp
```

I've been using a 'fixed' dataset as TransRate identified 'Non unique fasta identifiers'. As suggested I fixed these with the following code: 
`sed 's_|_-_g' Trinity.fasta > Trinity.fixed.fa`

I then proceeded to run Transrate and was greeted with the following error message:
```
FASTA file contained a character that's not a valid base (or N): '9', full line '9966, 9967, 10433, 10645, 10550, 10432, 10179, -2]';
converting to 'N'.  This may happen again, but there will be no more warnings.
Saving genome...0s
mmap: Cannot allocate memory
SNAP exited with exit code 1 from line 394 of file SNAPLib/BigAlloc.cpp
```
Assuming the non-valid bases were converted to 'N' I ran the script a second time which resulted in the above mentioned error message relating to being `Unable to open file 'Trinity.fixed/GenomeIndex' for read`. For reference the coding that I've been using is as follows:
```
transrate --assembly= /trinity/all/Trinity.fixed.fa \
--left /trimmomatic/paired/R1_trimmed_paired.fastq \
--right /trimmomatic/paired/R2_trimmed_paired.fastq \
--output=/TransRate/ReadMapped

```

Thanks in advance,
Jake

**Comment by blahah** [comment]
Hi @JakeGoodall, sorry for the slow reply.

I think the problem was a bug introduced in the last version of Transrate.

The latest release of transrate [v1.0.3](https://github.com/blahah/transrate/releases/tag/v1.0.3) now includes the latest version of SNAP and Salmon. Please update and try your analysis again. Hopefully this will solve the problem - if not please re-open the issue. Many thanks for your patience :)
