### ISSUE TITLE
Install transrate in docker image of ubuntu 16.04 / salmon:0.4 error

### ISSUE THREAD

**Issue by chklopp** [blahah/transrate#203]
Hi,

I'm trying to install transrate in a docker image of ubuntu 16.04.

Here are the commands I use : 
apt-get install ruby-dev ruby make gcc
gem install transrate
transrate --install-deps all

The last installation instruction reports an error : 
root@1a9ab23c5cdd:/# transrate --install-deps all
Checking dependencies
Installing snap (1.0beta.18)...
Installing bam-read (1.0.0)...
Installing salmon (0.4)...
Installing blastplus (2.2.[0-9])...
[ERROR] 2016-09-30 11:51:47 : Failed to install: 
- salmon:0.4

Any idea how to make this work?

**Comment by nktsk** [comment]
Hi, 

I am having the same problem. I've installed salmon 0.6.0 and the latest version 0.7.2, both added to my PATH, but cant get transrate to locate them. Did you manage to sort it out? 

Cheers,

**Comment by chklopp** [comment]
We succeeded installing transrate in docker. Here is our docker file.
http://www.sigenae.org/drap/lib/src/Dockerfile

Ch+
