### ISSUE TITLE
transrate in conda project

### ISSUE THREAD

**Issue by manuelsmendoza** [Blahah/transrate#226]
Hi!

Thanks so much for Transrate, it's a fantastic tool!! Have you thought about adding transrate to Conda (bioconda)? It's the easiest way to install bioinformatic software.

Cheers,
~MM

**Comment by lmfaber** [comment]
I made a Conda recipe myself. It's not the cleanest recipe, but works for me. If you happen to test it, I would appreciate some feedback. It's not on bioconda, but in a private repository. Have a look at #215

**Comment by manuelsmendoza** [comment]
Nice! I'll try! Thansk!!

**Comment by roryk** [comment]
Awesome-- what do you think about moving your conda recipe to bioconda?

**Comment by lmfaber** [comment]
I would like to have the recipe added to bioconda so people can have easier access to it. However, I think that the recipe doesn't meet the requirements from the [guideline](https://bioconda.github.io/guidelines.html). The biggest issue here being the dependencies. The recipe just downloads the precompiled binaries, including all dependencies like Snap-aligner, Salmon, Bam-read, and Blast+. If I get it right, one should use the dependencies from channels like bioconda, conda-forge or the default anaconda channel. However, I don't know if this is actually a big issue... Any thoughts on this?
