### ISSUE TITLE
Transrate broken and unsupported?

### ISSUE THREAD

**Issue by Shellfishgene** [Blahah/transrate#230]
Hi,
I just tried to use this for a project before I realized there are a number of bugs (nicely listed in issue https://github.com/blahah/transrate/issues/201), and apparently no support any more for some years now. Maybe it would be nice to put a warning on the webpage and in the main readme that Transrate is currently only semi-useable and not supported anymore, so people don't waste time trying to use it befor running into those issues.

**Comment by macmanes** [comment]
I'll just note that there is a working version of TransRate packaged in the Oyster River Transcriptome assembler. Install via docker: https://oyster-river-protocol.readthedocs.io/en/latest/docker_install.html

**Comment by Shellfishgene** [comment]
Thanks, unfortunately I can't use Docker on our cluster but I'll have a look.

**Comment by macmanes** [comment]
You can use https://oyster-river-protocol.readthedocs.io/en/latest/aws_setup.html for manual install, but it’s fairly finicky on some systems.

Matt
______________________________________________
Matthew MacManes, Ph.D.
University of New Hampshire  |  Associate Professor of Genome Enabled Biology
Department of Molecular, Cellular, & Biomedical Sciences
Durham, NH  03824
Phone: 603-862-4052<tel://Phone:%20603-862-4052>  |  Web: genomebio.org<http://genomebio.org/>
Office: 434 Gregg Hall  |  Laboratory: 437 Gregg Hall

On Sep 5, 2019, at 09:18, Shellfishgene <notifications@github.com<mailto:notifications@github.com>> wrote:

Caution - External Email
________________________________

Thanks, unfortunately I can't use Docker on our cluster but I'll have a look.

**Comment by Shellfishgene** [comment]
For now I used the version found in https://github.com/macmanes-lab/Oyster_River_Protocol/tree/master/software and that seems to run fine, thanks!
I'll have to build the ORP docker image with ubuntu 16 and convert to singularity to run it, I'll try that later...
