### ISSUE TITLE
transrate with 2left and 2 right fastq files?

### ISSUE THREAD

**Issue by VaneSGT** [Blahah/transrate#238]
Hello,
I want to check with transrate a transcritome that is assemble by de novo using 2 left and 2 right fastq files, that is forward root, forward shoot, reverse root and reverse shoot.
Just by separation using coma does not work, because transrate considered that coma separation is also for coma separated transcriptome assemblies, therefore transrate only consider the first fastq file for each.
I also tried to combine the files in a single file, but transrate does not work because the position of the reads (or read name) is duplicated and I think the software does not know what is the real forward+reverse couple between shoots and roots files.

Any suggestion¿

**Comment by blahah** [comment]
It's been at least 3 years since I last looked at the code or ran the tool, so please bear with me while I check this out. I hope to have a solution for you soon :)

**Comment by blahah** [comment]
Hey - you're right that it doesn't work as expected in this case. Sorry for the trouble!

I did some tests and by far the easiest solution is to just combine the left and right fq files into one file each, e.g.:

```bash
cat *_1.fq > all_1.fq
cat *_2.fq > all_2.fq
transrate --assembly assembly.fa --left all_1.fq --right all_2.fq
```

**Comment by VaneSGT** [comment]
Thanks a lot,
first time I combined the files did not work, probably because I combined wrong files :$
But now is OK
It is just that I was wondering if could be a way to just feed with files directly, but in the end this is a pain and combine files is fine and fast so...

:)
