### ISSUE TITLE
cli: --print-commands

### ISSUE THREAD

**Issue by blahah** [blahah/transrate#58]
Some users would like to run their BLAST distributed. Rather than try to handle that from transrate, we can simply print out the commands to be run and allow them to place the output files in the working directory before running transrate.

Add a `--print-commands` flag that implements this.

**Comment by cboursnell** [comment]
This would also be useful if someone wants to run snap beforehand and then give transrate the bam

**Comment by macmanes** [comment]
+1 for this. I'm trying to investigate some differences in TransRate/Detonate and having an easy way to know how Transrate does the mapping, via snap, would be helpful. 

Think `--dry-run` like in a makefile..

**Comment by Blahah** [comment]
You can get this behaviour currently by using `--loglevel debug`
